/// <reference types="react-scripts" />
declare module '@rsksmart/rlogin'
declare module 'ethjs-query'
declare module '@rsksmart/ethr-did'
declare module 'ethr-did-resolver'
declare module 'rskjs-util'
declare module 'ethjs'
declare module 'ethjs-contract'
declare module 'identicon.js'
declare module '@rsksmart/rsk-testnet-contract-metadata'
declare module '@rsksmart/rsk-contract-metadata'
